build_from:
  # aarch64: mbentley/omada-controller:5.0-arm64
  # amd64: mbentley/omada-controller:5.0-amd64
  # armv7: mbentley/omada-controller:5.0-armv7l
  aarch64: ghcr.io/home-assistant/aarch64-base-ubuntu:16.04
  amd64: ghcr.io/home-assistant/amd64-base-ubuntu:16.04
  armv7: ghcr.io/home-assistant/armv7-base-ubuntu:16.04
args:
  # ARCH: "{arch}"
  # BASE: "ubuntu:16.04"
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 2.1.0.2