build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-ubuntu:18.04
  amd64: ghcr.io/home-assistant/amd64-base-ubuntu:18.04
  armv7: ghcr.io/home-assistant/armv7-base-ubuntu:16.04
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Omada Controller 5"
  org.opencontainers.image.description: "Omada Controller 5 addon for Home Assistant"
  org.opencontainers.image.source: "https://github.com/SoulOfNoob/HASSIO-Addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 2.1.0.2